# Generated by Django 3.1.7 on 2021-04-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('NO_FILTER', 'no filter'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred'), ('BINARY', 'binary'), ('INVERT', 'invert'), ('BOX_BLUR', 'box_blur'), ('EMBOSS', 'emboss'), ('IDENTITY', 'identity'), ('HIGHPASS', 'highpass'), ('SHARPEN', 'sharpen')], max_length=50, null=True)),
            ],
        ),
    ]
