# Generated by Django 3.1.7 on 2021-04-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'no filter'), ('COLORIZED', 'colorized'), ('GRAYSCALE', 'grayscale'), ('BLURRED', 'blurred'), ('BINARY', 'binary'), ('INVERT', 'invert'), ('BOX_BLUR', 'box_blur'), ('EMBOSS', 'emboss'), ('IDENTITY', 'identity'), ('HIGHPASS', 'highpass'), ('SHARPEN', 'sharpen')], max_length=50, null=True),
        ),
    ]
